apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: gurleen16/notes-app-k8s
        ports:
        - containerPort: 8000

        env:
        - name: DB_NAME
          value: notesdb

        - name: DB_USER
          value: root

        - name: DB_PASSWORD
          value: root

        - name: DB_HOST
          value: mysql-service  

        - name: DB_PORT
          value: "3306"
